version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=dine_hub
      - DB_USERNAME=root
      - DB_PASSWORD=root      
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dine_hub
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
